# acpp-toolchain.cmake — self-contained toolchain configuration for direct
# cmake/IDE use (the activation scripts' CMAKE_ARGS covers pixi/conda-build).
#   cmake -DCMAKE_TOOLCHAIN_FILE=$CONDA_PREFIX/share/acpp/toolchain/acpp-toolchain.cmake ..
cmake_minimum_required(VERSION 3.18)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
if(DEFINED ENV{PREFIX} AND DEFINED ENV{SRC_DIR})
    set(_ACPP_PFX "$ENV{PREFIX}")
else()
    set(_ACPP_PFX "$ENV{CONDA_PREFIX}")
endif()
set(_ACPP_CHOST "x86_64-conda-linux-gnu")
set(CMAKE_C_COMPILER   "${_ACPP_PFX}/bin/${_ACPP_CHOST}-clang")
set(CMAKE_CXX_COMPILER "${_ACPP_PFX}/bin/${_ACPP_CHOST}-clang++")
set(CMAKE_LINKER       "${_ACPP_PFX}/bin/ld.lld")
set(CMAKE_AR           "${_ACPP_PFX}/bin/llvm-ar")
set(CMAKE_NM           "${_ACPP_PFX}/bin/llvm-nm")
set(CMAKE_RANLIB       "${_ACPP_PFX}/bin/llvm-ranlib")
set(CMAKE_STRIP        "${_ACPP_PFX}/bin/llvm-strip")
set(CMAKE_C_COMPILER_TARGET   "${_ACPP_CHOST}")
set(CMAKE_CXX_COMPILER_TARGET "${_ACPP_CHOST}")
if(DEFINED ENV{CONDA_BUILD_SYSROOT})
    set(CMAKE_SYSROOT "$ENV{CONDA_BUILD_SYSROOT}")
else()
    set(CMAKE_SYSROOT "${_ACPP_PFX}/${_ACPP_CHOST}/sysroot")
endif()
set(CMAKE_FIND_ROOT_PATH "${_ACPP_PFX}" "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
set(CMAKE_C_FLAGS_INIT   "-isystem ${_ACPP_PFX}/include")
set(CMAKE_CXX_FLAGS_INIT "-isystem ${_ACPP_PFX}/include")
set(_ACPP_LD_FLAGS "-Wl,-rpath,${_ACPP_PFX}/lib -Wl,-rpath-link,${_ACPP_PFX}/lib -L${_ACPP_PFX}/lib -fuse-ld=lld")
set(CMAKE_EXE_LINKER_FLAGS_INIT    "${_ACPP_LD_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_ACPP_LD_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_ACPP_LD_FLAGS}")
set(AdaptiveCpp_DIR "${_ACPP_PFX}/lib/cmake/AdaptiveCpp" CACHE PATH "AdaptiveCpp CMake config")
if(NOT DEFINED ACPP_TARGETS AND NOT DEFINED ENV{ACPP_TARGETS})
    set(ACPP_TARGETS "generic" CACHE STRING "AdaptiveCpp targets")
endif()
